name: Test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test-pkg:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup deps
        run: sudo apt-get install -y autoconf automake build-essential cmake pkg-config
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2'
      - name: Run tests
        run: go test -count=1 ./pkg/...
